### PR TITLE
Working example

### PR DESCRIPTION
**Pull request by ivannovak**
Super cool architecture demo! Figured an updated PR to get it working might be well received.

- bumped to php 7.4 references throughout
- a little more specificity for postgres connections
- updated sql init sql (guessed at appropriate size)
- removed the nginx resolver addy
- updated the `Fn` namespace to avoid conflicts with the (relatively) new short functions
- updated namespace references where necessary
- updated argument order and contents where necessary

Specifically, not a fan of the change on `service/user-write/public/index.php:41` but it works ™️

### CODE REVIEW

**Comment by codeliner** [comment]
nice! It was really time for an update ;)
Hope I find some time next week to review your PR. Thx!

**Comment by codeliner** [comment]
Looks good to me. @prolic do you want to take a second look?

**Comment by prolic** [comment]
Yep, I try to have a look tomorrow.

Sorry if that delays again a little.

**Comment by codeliner** [comment]
ping @prolic ;)

**Review by prolic — APPROVED** [review]

**Comment by prolic** [comment]
Thanks!!

**Pull request merged**
