### PR TITLE
Fix some things so that user write service works properly.

### PR DESCRIPTION
**Pull request by wysow**
Not really sure about the length of the `category` field, what do you think?

EDIT: for your information I did use `composer update` before doing this fix.

### CODE REVIEW

**Comment by prolic** [comment]
Let's get back to this, when the open PR's of e event store are merged.

**Comment by wysow** [comment]
Sure...

Sounds great to you if I try to implement some of the other features in others services?

**Comment by prolic** [comment]
Go for it. Any help is greatly appreciated.

**Comment by prolic** [comment]
Closing since out of date already.

**Pull request closed without merging**
